### ISSUE TITLE
Feature request: simplify authentication

### ISSUE THREAD

**Issue by mdb** [JonathanBennett/AkamaiOPEN-edgegrid-node#11]
In current implementation, `AkamaiOPEN-edgegrid-node` requires the user to call 2 methods with each request: 1) [`#auth`](https://github.com/JonathanBennett/AkamaiOPEN-edgegrid-node/blob/master/src/api.js#L93) 2) [`#send`](https://github.com/JonathanBennett/AkamaiOPEN-edgegrid-node/blob/master/src/api.js#L103).

(Additionally, `#auth` accepts an undocumented & seemingly unnecessary callback -- can this be removed?) 

In my mind, it would substantially simplify usage if authentication were abstracted behind `#send`, thus saving the user from needing to call 2 methods.

Please let me know your thoughts -- I am happy to implement this.

Thanks!

**Comment by JonathanBennett** [comment]
Hi @mdb - You're right, it does seem unnecessary. Originally when I made this module I started by making it so that the functions could be chained (.auth().send()) to follow similar standards that are popping it up other libraries, but decided against it. 

The undocumented callback (which I could swear I documented but apparently not) is there so that if you want to sign and send your request immediately you can chain on the callback and send straight away from there.

If we are to supply an abstraction, I personally would prefer there was a helper method that merged these two lower level methods. It's easier to understand how these two function together if they are also accessible separately, but would appreciate your input.

Thanks.

**Comment by mdb** [comment]
I see.

Regarding the chaining, I don't believe the callback is necessary to provide this functionality. According to my understanding, a simple `return this;` from within `auth` should make `auth` chainable.

As for your point regarding a helper method:

I'm receptive to your opinions: 3 public methods could be `auth`, `send`, and a convenience method such as `sendAuth`. 

That said, I'm not fully convinced a public `auth` is necessary at all. In my mind, the purpose of the `AkamaiOPEN-edgegrid-node` is to abstract from users such details regarding how successful, authenticated Akamai API requests operate in favor of offering a simple, high-level methods for interacting with Akamai. Furthermore, amongst users who _do_ want to understand low level details, a private `auth` method called from within the public `send` method is arguably no less understandable than the current implementation.

But again, I'm flexible in my views. Thanks for your response!

**Comment by JonathanBennett** [comment]
Ah no, sorry, the two are unrelated (chaining and callback) - I probably didn't make sense sending my reply from my phone. :-)

I feel you make good points and yes, it is meant to make it easy to operate with the Akamai API. 

My main reason for maintaining both, at least in the short term, is backwards compatibility. Even if it's undocumented for the time being it should probably remain available. 

If you wanted to make a patch for this, however, please feel free and we'll review. 

Cheers!

Jonathan.

**Comment by mdb** [comment]
Your concern about backwards compatibility is valid.

How about this as a third public method?

```
EdgeGrid.prototype.request = function(req, callback) {
  this.auth(req);
  this.send(callback);
};
```

**Comment by JonathanBennett** [comment]
Awesome. Thanks! 

Jonathan.

**Comment by JonathanBennett** [comment]
Closing this with the merged PRs. Thanks!
